Added more possible streetalike keys and some new keys
graphhopper/geocoder-converter pull request #24
Opened 2016-12-20 07:30 UTC by boldtrn

This PR intents to fix #23. 

I added the following keys **postcode** and **osm_value**. Also I added more possible street name keys. It seems that nominatim and opencagedata return a diverse set of streetname keys, not sure if there is a complete list of keys out there, it seems to be different from the osm highways tag.

I have not aded the osm_key as opencagedata seems to not return the osm_key, but I can add it for Nominatim?

2016-12-20 09:41 UTC, karussell requested changes
Thanks! Just some minor comments ...

2016-12-20 09:41 UTC, karussell commented on src/main/java/com/graphhopper/converter/api/NominatimEntry.java
> +    private String type;
Would you mind to add an example in the comments here? Is this node vs. way?

2016-12-20 09:41 UTC, karussell commented on src/main/java/com/graphhopper/converter/api/NominatimEntry.java
> +        return this.address.construction;
Would you mind to move this into a new method address.getStreetName?

2016-12-20 09:41 UTC, karussell commented on src/main/java/com/graphhopper/converter/api/NominatimEntry.java
> +        public String construction;
Oh, this is ugly ... and I also did not find documentation for this. One further tag you can add is cycleway: http://nominatim.openstreetmap.org/search.php?q=bayreuth%20fahrradhighway&polygon=1&format=json&addressdetails=1

2016-12-20 09:41 UTC, karussell commented on src/main/java/com/graphhopper/converter/api/OpenCageDataEntry.java
> +        public String construction;
Can we somehow reuse the Address stuff here?

2016-12-20 10:40 UTC, karussell commented
How do we handle the different name entry e.g. we could parse "restaurant":"Sushi Oji" and use this as name but we would overwrite the full display name: "Sushi Oji, Prinzregentenstraße 122, 81677 München, Deutschland" and potentially break existing apps... hmmh

2016-12-21 02:13 UTC, boldtrn commented on src/main/java/com/graphhopper/converter/api/NominatimEntry.java
> +        return this.address.construction;
Not at all, I had the same thought :)

2016-12-21 02:14 UTC, boldtrn commented on src/main/java/com/graphhopper/converter/api/NominatimEntry.java
> +        public String construction;
Thanks, added cycleway.

2016-12-21 02:15 UTC, boldtrn commented on src/main/java/com/graphhopper/converter/api/OpenCageDataEntry.java
> +        public String construction;
I wans't sure if this works with Jackson, but I was able to move all duplicated entries to an abstract class.

2016-12-21 02:17 UTC, boldtrn commented
> How do we handle the different name entry?

I always thought this would be one of the benefits of using a different geocoder. For example having the more detailed display_name of Nominatim.

2016-12-21 02:27 UTC, boldtrn commented
I updated my branch and fixed your requested changes.

2016-12-21 06:36 UTC, karussell approved these changes

2016-12-21 06:41 UTC, karussell commented
> > How do we handle the different name entry?

> I always thought this would be one of the benefits of using a different geocoder. For example having the more detailed display_name of Nominatim.

Using different geocoders should give you different quality. The fields should be the same information, so if it is a POI it should contain just its name not the full address and if it is a street, then it could just contain the street name etc. having a field `all_name` or `display_name` with all information could be a nice addition though, which we would need for photon too then.

2016-12-21 06:42 UTC, merged